# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Exchange Rates' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 # pod 'SwiftLint'
 # pod 'Reachability'
 
pod 'Fabric'
pod 'Crashlytics'
pod 'Reachability'

  # Pods for RatesTestProject

end
